### ISSUE TITLE
silverstripe/framework version requirement too restrictive

### ISSUE THREAD

**Issue by phil-quinn** [dynamic/silverstripe-state-dropdown-field#6]
I tested the master branch in an SS4 project and it works fine as near as I can tell. Can you do something with the composer.json to allow for installation on SS4 projects? Thanks!

**Comment by phil-quinn** [comment]
ok, turns out I forgot that I also had to change one line of name spacing... You can see it here:
https://github.com/Quinn-Interactive/silverstripe-state-dropdown-field/blob/master/src/form/fields/StateDropdownField.php#L3

I also made the silver stripe/framework requirement more permissive (maybe too permissive) here:
https://github.com/Quinn-Interactive/silverstripe-state-dropdown-field/blob/master/composer.json#L20

**Comment by phil-quinn** [comment]
And on top of all that, I hit the wrong button to submit my comment and accidentally closed this. Not my best work today. ;)

**Comment by muskie9** [comment]
Hi @phil-quinn, it looks like you have the makings of a PR here. If you update the framework requirement to `^4.0` and change [this section](https://github.com/Quinn-Interactive/silverstripe-state-dropdown-field/blob/master/composer.json#L35-L37) to be the following and submit a PR to the master branch, that should probably cover getting it 4 compatible functionally. Once the PR is opened I can help work through upgrading the test for the class.

```yml
    "branch-alias": {
      "1.0": "1.0.x-dev",
      "dev-master": "2.0.x-dev"
    }
```
